=== rjakubco/FaFram8/deployer/src/main/resources/parser/configuration.scheme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:org.jboss.fuse.qa" elementFormDefault="qualified" xmlns:tns="urn:org.jboss.fuse.qa">
	<xs:element name="fafram">
		<xs:complexType>
			<xs:all>
				<xs:element name="configuration" type="tns:configurationType" minOccurs="0"/>
				<xs:element name="users" type="tns:usersType" minOccurs="0"/>
				<xs:element name="commands" type="tns:commandsType" minOccurs="0"/>
				<xs:element name="bundles" type="tns:bundlesType" minOccurs="0"/>
				<xs:element name="ensemble" type="xs:string" minOccurs="0"/>
				<xs:element name="containers" type="tns:containersType" minOccurs="0"/>
				<xs:element name="brokers" type="tns:brokersType" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="configurationType">
		<xs:all>
			<xs:element name="provider" type="xs:string" minOccurs="0"/>
			<xs:element name="hostUser" type="xs:string" minOccurs="0"/>
			<xs:element name="hostPassword" type="xs:string" minOccurs="0"/>
			<xs:element name="hostPort" type="xs:string" minOccurs="0"/>
			<xs:element name="fuseUser" type="xs:string" minOccurs="0"/>
			<xs:element name="fusePassword" type="xs:string" minOccurs="0"/>
			<xs:element name="fuseZip" type="xs:string" minOccurs="0"/>
			<xs:element name="startWaitTime" type="xs:string" minOccurs="0"/>
			<xs:element name="stopWaitTime" type="xs:string" minOccurs="0"/>
			<xs:element name="provisionWaitTime" type="xs:string" minOccurs="0"/>
			<xs:element name="skipBrokerWait" minOccurs="0"/>
			<xs:element name="offline" minOccurs="0"/>
			<xs:element name="withoutDefaultUser" minOccurs="0"/>
			<xs:element name="iptables" type="tns:noValuePathAttr" minOccurs="0"/>
			<xs:element name="jdk" type="tns:noValuePathAttr" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="noValuePathAttr">
		<xs:attribute name="path" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="usersType">
		<xs:sequence>
			<xs:element name="user">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="password" type="xs:string"/>
					<xs:attribute name="roles" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="commandsType">
		<xs:sequence>
			<xs:element name="command" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bundlesType">
		<xs:sequence>
			<xs:element name="bundle" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="containersType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="root" type="tns:rootType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="child" type="tns:childType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ssh" type="tns:sshType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="count" type="xs:integer"/>
	</xs:complexType>

	<xs:complexType name="profilesType">
		<xs:sequence>
			<xs:element name="profile" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rootType">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="jvmOpts" type="xs:string" minOccurs="0"/>
			<xs:element name="commands" type="tns:commandsType" minOccurs="0"/>
			<xs:element name="profiles" type="tns:profilesType" minOccurs="0"/>
			<xs:element name="jvmMemoryOpts" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="xms" type="xs:string"/>
					<xs:attribute name="xmx" type="xs:string"/>
					<xs:attribute name="permMem" type="xs:string"/>
					<xs:attribute name="maxPermMem" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="workingDir" type="xs:string" minOccurs="0"/>
			<xs:element name="users" type="tns:usersType" minOccurs="0"/>
			<xs:element name="node" type="tns:nodeType" minOccurs="0"/>
			<xs:element name="bundles" type="tns:bundlesType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="fabric" type="xs:boolean"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="ref" type="xs:string"/>
		<xs:attribute name="instances" type="xs:integer"/>
		<xs:attribute name="template" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="nodeType">
		<xs:attribute name="host" type="xs:string"/>
		<xs:attribute name="port" type="xs:integer"/>
		<xs:attribute name="user" type="xs:string"/>
		<xs:attribute name="password" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="childType">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="jvmOpts" type="xs:string" minOccurs="0"/>
			<xs:element name="commands" type="tns:commandsType" minOccurs="0"/>
			<xs:element name="profiles" type="tns:profilesType" minOccurs="0"/>
			<xs:element name="parentName" type="xs:string" minOccurs="0"/>
			<xs:element name="version" type="xs:string" minOccurs="0"/>
			<xs:element name="jmxUser" type="xs:string" minOccurs="0"/>
			<xs:element name="jmxPassword" type="xs:string" minOccurs="0"/>
			<xs:element name="resolver" type="tns:resolverType" minOccurs="0"/>
			<xs:element name="manualIp" type="xs:string" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="sameNodeAs" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="ref" type="xs:string"/>
		<xs:attribute name="instances" type="xs:integer"/>
		<xs:attribute name="template" type="xs:boolean"/>
	</xs:complexType>

	<xs:simpleType name="resolverType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="localip"/>
			<xs:enumeration value="manualip"/>
			<xs:enumeration value="localhostname"/>
			<xs:enumeration value="publicip"/>
			<xs:enumeration value="publichostname"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="sshType">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="jvmOpts" type="xs:string" minOccurs="0"/>
			<xs:element name="commands" type="tns:commandsType" minOccurs="0"/>
			<xs:element name="profiles" type="tns:profilesType" minOccurs="0"/>
			<xs:element name="parentName" type="xs:string" minOccurs="0"/>
			<xs:element name="node" type="tns:nodeType" minOccurs="0"/>
			<xs:element name="version" type="xs:string" minOccurs="0"/>
			<xs:element name="env" type="xs:string" minOccurs="0"/>
			<xs:element name="path" type="xs:string" minOccurs="0"/>
			<xs:element name="resolver" type="tns:resolverType" minOccurs="0"/>
			<xs:element name="manualIp" type="xs:string" minOccurs="0"/>
			<xs:element name="workingDir" type="xs:string" minOccurs="0"/>
			<xs:element name="zookeeperPassword" type="xs:string" minOccurs="0"/>
			<xs:element name="privateKey" type="xs:string" minOccurs="0"/>
			<xs:element name="passPhrase" type="xs:string" minOccurs="0"/>
			<xs:element name="proxyUri" type="xs:string" minOccurs="0"/>
			<xs:element name="minPort" type="xs:positiveInteger" minOccurs="0"/>
			<xs:element name="maxPort" type="xs:positiveInteger" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="sameNodeAs" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="ref" type="xs:string"/>
		<xs:attribute name="instances" type="xs:integer"/>
		<xs:attribute name="template" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="brokersType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="broker" type="tns:brokerType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="brokerType">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="ssl" type="xs:boolean" minOccurs="0"/>
			<xs:element name="kind" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MasterSlave"/>
						<xs:enumeration value="StandAlone"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="parentProfile" type="xs:string" minOccurs="0"/>
			<xs:element name="group" type="xs:string" minOccurs="0"/>
			<xs:element name="data" type="xs:string" minOccurs="0"/>
			<xs:element name="networks" type="tns:networksType" minOccurs="0"/>
			<xs:element name="pids" type="tns:pidsType" minOccurs="0"/>
			<xs:element name="containerFilter" type="xs:string" minOccurs="0"/>
			<xs:element name="ports" type="tns:portsType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="ref" type="xs:string"/>
		<xs:attribute name="template" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="networksType">
		<xs:sequence>
			<xs:element name="network">
				<xs:complexType>
					<xs:attribute name="url" type="xs:string"/>
					<xs:attribute name="username" type="xs:string"/>
					<xs:attribute name="password" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="pidsType">
		<xs:sequence>
			<xs:element name="pid" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="pid" type="xs:string"/>
					<xs:attribute name="value" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="portsType">
		<xs:sequence>
			<xs:element name="port" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="protocol" type="xs:string"/>
					<xs:attribute name="port" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== rjakubco/FaFram8/deployer/src/main/resources/parser/configuration_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<fafram xmlns="urn:org.jboss.fuse.qa"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="urn:org.jboss.fuse.qa configuration.scheme.xsd">

	<!-- All of the system properties that can be set using XML -->
	<configuration>
		<provider>OpenStack</provider>
		<hostUser>user</hostUser>
		<hostPassword>pw</hostPassword>
		<hostPort>22</hostPort>
		<fuseUser>user</fuseUser>
		<fusePassword>user</fusePassword>
		<fuseZip>http://fusezip</fuseZip>
		<startWaitTime>120</startWaitTime>
		<stopWaitTime>30</stopWaitTime>
		<provisionWaitTime>300</provisionWaitTime>
		<skipBrokerWait/>
		<offline/>
		<iptables path="path"/>
		<withoutDefaultUser/>
		<jdk path="path"/>
	</configuration>
	<!-- Equivalent of Fafram.addUser(), adds user to all root containers -->
	<users>
		<user name="user1" password="pw" roles="Administrator"/>
		<user name="user2" password="pw" roles="Administrator"/>
	</users>
	<!-- Equivalent of Fafram.commands(), executes these commands on all root containers -->
	<commands>
		<command>profile-edit</command>
		<command>profile-delete</command>
	</commands>
	<!-- Equivalent of Fafram.bundles(), uploads the bundles to maven proxy -->
	<bundles>
		<bundle>bundle</bundle>
	</bundles>
	<!-- Equivalent of Fafram.ensemble(), creates an ensemble of these containers -->
	<ensemble>root,c1,c2</ensemble>

	<!-- Containers definition -->
	<containers>
		<!--	In every container you can use "ref" as a reference to already defined container
				Standard workflow is to define one "template" container (template="true") to set
				all common attributes:
				<root template="true" id="myTemplate">
					<jvmMemoryOpts xms="512M" xmx="1024M" permMem="512M" maxPermMem="1024M"/>
				</root>
				And then inherit the jvmMemoryOpts from the template in all root containers using
				ref="myTemplate"
				<root ref="myTemplate>
					...
				</root>
				The same applies for child and ssh containers.
				Current drawback is that the template should be the same container type as the children.
		-->
		<root fabric="true" instances="1">
			<name>ecervena-root123</name>
			<jvmMemoryOpts xms="512M" xmx="1024M" permMem="512M" maxPermMem="1024M"/>
			<jvmOpts>-Dproperty=Value</jvmOpts>
			<workingDir>fafram</workingDir>
			<node host="" port="22" user="fuse" password="fuse"/>
			<users>
				<user name="user" password="pw" roles="Administrator"/>
			</users>
			<commands>
				<command>profile-edit root</command>
			</commands>
			<bundles>
				<bundle>bundle</bundle>
			</bundles>
			<profiles>
				<profile>p</profile>
			</profiles>
		</root>

		<child instances="1">
			<name>ecervena-node1123</name>
			<parentName>ecervena-root123</parentName>
			<version>1.0</version>
			<jvmOpts>-Dproperty=Value</jvmOpts>
			<jmxUser>admin</jmxUser>
			<jmxPassword>pw</jmxPassword>
			<resolver>localip</resolver>
			<manualIp>127.0.0.1</manualIp>
			<commands>
				<command>profile-edit</command>
			</commands>
			<profiles>
				<profile>p</profile>
			</profiles>
		</child>

		<ssh instances="1">
			<name>ecervena-node1123</name>
			<node host="" user="user" password="pw"/>
			<version>1.0</version>
			<env>-Dproperty=value</env>
			<jvmOpts>-Dproperty=Value</jvmOpts>
			<workingDir>containers</workingDir>
			<zookeeperPassword>pw</zookeeperPassword>
			<resolver>localip</resolver>
			<manualIp>127.0.0.1</manualIp>
			<privateKey>id_rsa</privateKey>
			<passPhrase>phrase</passPhrase>
			<proxyUri>http://localhost:9999</proxyUri>
			<minPort>9999</minPort>
			<maxPort>11000</maxPort>
			<commands>
				<command>profile-edit</command>
			</commands>
			<profiles>
				<profile>p</profile>
			</profiles>
		</ssh>
	</containers>

	<brokers>
		<!-- You can use the template, id, ref here aswell -->
		<broker>
			<name>name</name>
			<ssl>true</ssl>
			<kind>MasterSlave</kind>
			<group>myGroup</group>
			<data>/data</data>
			<parentProfile>default</parentProfile>
			<networks>
				<network url="tcp://localhost:61616" username="user" password="password"/>
			</networks>
			<pids>
				<pid pid="mypid" value="myvalue"/>
			</pids>
			<ports>
				<port protocol="openwire" port="11111"/>
			</ports>
		</broker>
	</brokers>
</fafram>
