=== rjakubco/FaFram8/deployer/src/test/resources/config.scheme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:org.jboss.fuse.qa" elementFormDefault="qualified">
	<xs:element name="fafram">
		<xs:complexType>
			<xs:all>
				<xs:element name="configuration" type="configurationType"/>
				<xs:element name="users" type="usersType"/>
				<xs:element name="commands" type="commandsType"/>
				<xs:element name="bundles" type="bundlesType"/>
				<xs:element name="ensemble" type="xs:string"/>
				<xs:element name="containers" type="containersType"/>
				<xs:element name="brokers" type="brokersType"/>
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="configurationType">
		<xs:all>
			<xs:element name="provider" type="xs:string"/>
			<xs:element name="hostUser" type="xs:string"/>
			<xs:element name="hostPassword" type="xs:string"/>
			<xs:element name="hostPort" type="xs:string"/>
			<xs:element name="fuseUser" type="xs:string"/>
			<xs:element name="fusePassword" type="xs:string"/>
			<xs:element name="fuseZip" type="xs:string"/>
			<xs:element name="startWaitTime" type="xs:string"/>
			<xs:element name="stopWaitTime" type="xs:string"/>
			<xs:element name="provisionWaitTime" type="xs:string"/>
			<xs:element name="skipBrokerWait"/>
			<xs:element name="offline"/>
			<xs:element name="withoutDefaultUser"/>
			<xs:element name="iptables" type="noValuePathAttr"/>
			<xs:element name="jdk" type="noValuePathAttr"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="noValuePathAttr">
		<xs:attribute name="path" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="usersType">
		<xs:sequence minOccurs="0">
			<xs:element name="user">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="password" type="xs:string"/>
					<xs:attribute name="roles" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="commandsType">
		<xs:sequence minOccurs="0">
			<xs:element name="command" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bundlesType">
		<xs:sequence minOccurs="0">
			<xs:element name="bundle" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="containersType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="root" type="rootType"/>
			<xs:element name="child" type="childType"/>
			<xs:element name="ssh" type="sshType"/>
		</xs:sequence>
		<xs:attribute name="count" type="xs:integer"/>
	</xs:complexType>

	<xs:complexType name="containerType">
		<xs:all>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="jvmOpts" type="xs:string"/>
			<xs:element name="commands" type="commandsType"/>
			<xs:element name="profiles" type="profilesType"/>
		</xs:all>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="ref" type="xs:string"/>
		<xs:attribute name="instances" type="xs:integer"/>
		<xs:attribute name="template" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="profilesType">
		<xs:sequence minOccurs="0">
			<xs:element name="profile" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rootType">
		<xs:complexContent>
			<xs:extension base="containerType">
				<xs:all>
					<xs:element name="jvmMemoryOpts">
						<xs:complexType>
							<xs:attribute name="xms" type="xs:string"/>
							<xs:attribute name="xmx" type="xs:string"/>
							<xs:attribute name="permMem" type="xs:string"/>
							<xs:attribute name="maxPermMem" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="workingDir" type="xs:string"/>
					<xs:element name="users" type="usersType"/>
					<xs:element name="node" type="nodeType"/>
					<xs:element name="bundles" type="bundlesType"/>
				</xs:all>
				<xs:attribute name="fabric" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="nodeType">
		<xs:attribute name="host" type="xs:string"/>
		<xs:attribute name="port" type="xs:integer"/>
		<xs:attribute name="user" type="xs:string"/>
		<xs:attribute name="password" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="childType">
		<xs:complexContent>
			<xs:extension base="containerType">
				<xs:all>
					<xs:element name="parentName" type="xs:string"/>
					<xs:element name="version" type="xs:string"/>
					<xs:element name="jvmOpts" type="xs:string"/>
					<xs:element name="jmxUser" type="xs:string"/>
					<xs:element name="jmxPassword" type="xs:string"/>
					<xs:element name="resolver" type="resolverType"/>
					<xs:element name="manualIp" type="xs:string"/>
				</xs:all>
				<xs:attribute name="fabric" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="resolverType">
		<xs:restriction>
			<xs:enumeration value="localip"/>
			<xs:enumeration value="manualip"/>
			<xs:enumeration value="localhostname"/>
			<xs:enumeration value="publicip"/>
			<xs:enumeration value="publichostname"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="sshType">
		<xs:complexContent>
			<xs:extension base="containerType">
				<xs:all>
					<xs:element name="node" type="nodeType"/>
					<xs:element name="version" type="xs:string"/>
					<xs:element name="env" type="xs:string"/>
					<xs:element name="jvmOpts" type="xs:string"/>
					<xs:element name="resolver" type="resolverType"/>
					<xs:element name="manualIp" type="xs:string"/>
					<xs:element name="workingDir" type="xs:string"/>
					<xs:element name="zookeeperPassword" type="xs:string"/>
					<xs:element name="privateKey" type="xs:string"/>
					<xs:element name="passPhrase" type="xs:string"/>
					<xs:element name="proxyUri" type="xs:string"/>
					<xs:element name="minPort" type="xs:positiveInteger"/>
					<xs:element name="maxPort" type="xs:positiveInteger"/>
				</xs:all>
				<xs:attribute name="fabric" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="brokersType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="broker" type="brokerType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="brokerType">
		<xs:all>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="ssl" type="xs:boolean"/>
			<xs:element name="kind">
				<xs:simpleType>
					<xs:restriction>
						<xs:enumeration value="MasterSlave"/>
						<xs:enumeration value="StandAlone"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="parentProfile" type="xs:string"/>
			<xs:element name="group" type="xs:string"/>
			<xs:element name="data" type="xs:string"/>
			<xs:element name="networks" type="networksType"/>
			<xs:element name="pids" type="pidsType"/>
			<xs:element name="containerFilter" type="xs:string"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="networksType">
		<xs:sequence>
			<xs:element name="network">
				<xs:complexType>
					<xs:attribute name="url" type="xs:string"/>
					<xs:attribute name="username" type="xs:string"/>
					<xs:attribute name="password" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="pidsType">
		<xs:sequence>
			<xs:element name="pid">
				<xs:complexType>
					<xs:attribute name="pid" type="xs:string"/>
					<xs:attribute name="value" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== rjakubco/FaFram8/deployer/src/test/resources/ParserTestConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<fafram xmlns="urn:org.jboss.fuse.qa"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="urn:org.jboss.fuse.qa config.scheme.xsd">

	<configuration>
		<provider>OpenStack</provider>
		<hostUser>user</hostUser>
		<hostPassword>pw</hostPassword>
		<hostPort>22</hostPort>
		<fuseUser>user</fuseUser>
		<fusePassword>user</fusePassword>
		<fuseZip>http://fusezip</fuseZip>
		<startWaitTime>120</startWaitTime>
		<stopWaitTime>30</stopWaitTime>
		<provisionWaitTime>300</provisionWaitTime>
		<skipBrokerWait/>
		<offline/>
		<iptables path="path"/>
		<withoutDefaultUser/>
		<jdk path="path"/>
	</configuration>
	<users>
		<user name="user1" password="pw" roles="Administrator"/>
		<user name="user2" password="pw" roles="Administrator"/>
	</users>
	<commands>
		<command>profile-edit</command>
		<command>profile-delete</command>
	</commands>
	<bundles>
		<bundle>bundle</bundle>
	</bundles>
	<ensemble>root,c1,c2</ensemble>

	<containers>
		<!--<ssh type="template" id="temp">-->
			<!--<commands>-->
				<!--<command>profile-edit</command>-->
			<!--</commands>-->
		<!--</ssh>-->

		<!--<ssh type="ssh" ref="temp">-->
			<!--<commands>-->
				<!--<command>profile-edit2</command>-->
			<!--</commands>-->
		<!--</ssh>-->
		<root template="true" id="root1">
			<name>temp1</name>
			<commands>
				<command>temp1</command>
			</commands>
		</root>
		<root template="true" id="root2" ref="root1">
			<name>root2</name>
			<jvmOpts>someopts</jvmOpts>
		</root>
		<root fabric="true" instances="1" ref="root2">
			<name>ecervena-root123</name>
			<jvmMemoryOpts xms="512M" xmx="1024M" permMem="512M" maxPermMem="1024M"/>
			<jvmOpts>-Dproperty=Value</jvmOpts>
			<workingDir>fafram</workingDir>
			<node host="" port="22" user="fuse" password="fuse"/>
			<users>
				<user name="user" password="pw" roles="Administrator"/>
			</users>
			<commands>
				<command>profile-edit root</command>
			</commands>
			<bundles>
				<bundle>bundle</bundle>
			</bundles>
			<profiles>
				<profile>p</profile>
			</profiles>
		</root>
		<!--<root fabric="true" instances="1" ref="root2">-->
			<!--<name>ecervena-root123</name>-->
			<!--<jvmMemoryOpts xms="512M" xmx="1024M" permMem="512M" maxPermMem="1024M"/>-->
			<!--<jvmOpts>-Dproperty=Value</jvmOpts>-->
			<!--<workingDir>fafram</workingDir>-->
			<!--<node host="" port="22" user="fuse" password="fuse"/>-->
			<!--<users>-->
				<!--<user name="user" password="pw" roles="Administrator"/>-->
			<!--</users>-->
			<!--<commands>-->
				<!--<command>profile-edit root</command>-->
			<!--</commands>-->
			<!--<bundles>-->
				<!--<bundle>bundle</bundle>-->
			<!--</bundles>-->
			<!--<profiles>-->
				<!--<profile>p</profile>-->
			<!--</profiles>-->
		<!--</root>-->

		<!--<child instances="1">-->
			<!--<name>ecervena-node1123</name>-->
			<!--<parentName>ecervena-root123</parentName>-->
			<!--<version>1.0</version>-->
			<!--<jvmOpts>-Dproperty=Value</jvmOpts>-->
			<!--<jmxUser>admin</jmxUser>-->
			<!--<jmxPassword>pw</jmxPassword>-->
			<!--<resolver>localip</resolver>-->
			<!--<manualIp>127.0.0.1</manualIp>-->
			<!--<commands>-->
				<!--<command>profile-edit</command>-->
			<!--</commands>-->
			<!--<profiles>-->
				<!--<profile>p</profile>-->
			<!--</profiles>-->
		<!--</child>-->

		<!--<ssh instances="1">-->
			<!--<name>ecervena-node1123</name>-->
			<!--<node host="" user="user" password="pw"/>-->
			<!--<version>1.0</version>-->
			<!--<env>-Dproperty=value</env>-->
			<!--<jvmOpts>-Dproperty=Value</jvmOpts>-->
			<!--<workingDir>containers</workingDir>-->
			<!--<zookeeperPassword>pw</zookeeperPassword>-->
			<!--<resolver>localip</resolver>-->
			<!--<manualIp>127.0.0.1</manualIp>-->
			<!--<privateKey>id_rsa</privateKey>-->
			<!--<passPhrase>phrase</passPhrase>-->
			<!--<proxyUri>http://localhost:9999</proxyUri>-->
			<!--<minPort>9999</minPort>-->
			<!--<maxPort>11000</maxPort>-->
			<!--<commands>-->
				<!--<command>profile-edit</command>-->
			<!--</commands>-->
			<!--<profiles>-->
				<!--<profile>p</profile>-->
			<!--</profiles>-->
		<!--</ssh>-->
	</containers>

	<brokers>
		<broker>
			<name>name</name>
			<ssl>true</ssl>
			<kind>MasterSlave</kind>
			<group>myGroup</group>
			<data>/data</data>
			<parentProfile>default</parentProfile>
			<networks>
				<network url="tcp://localhost:61616" username="user" password="password"/>
			</networks>
			<pids>
				<pid pid="mypid" value="myvalue"/>
			</pids>
		</broker>
	</brokers>
</fafram>
